### ISSUE TITLE
Build failed on Ubuntu22.04

### ISSUE THREAD

**Issue by aucker** [neutrinolabs/pulseaudio-module-xrdp#100]
Hi, I follow the Wiki to install this module, when I try to build this module with the command `./bootstrap && ./configure PULSE_DIR=~/pulseaudio.src `, I got the following error:
```
configure: WARNING: PULSE_DIR may not be valid - can't find expected file
configure: PULSE_CONFIG_DIR not defined
checking Searching for config.h under PULSE_DIR... find: '~/pulseaudio.src': No such file or directory
no
configure: error: Can't find config.h under PULSE_DIR. Define PULSE_CONFIG_DIR?
```

The content of 'pulseaudio.src' is as follows:
```
[~/pulseaudio.src]$ tree -L 2
.
├── build
│   ├── config.h
│   ├── doxygen
│   ├── man
│   ├── meson-info
│   ├── meson-logs
│   ├── meson-private
│   ├── po
│   ├── shell-completion
│   ├── src
│   └── vala
└── src
    ├── daemon
    ├── modules
    ├── pulse
    ├── pulsecore
    ├── tests
    └── utils

17 directories, 1 file
```
What should I do next?

**Comment by matt335672** [comment]
It looks like the pulseaudio sources haven't built correctly.

Did you run `scripts/install_pulseaudio_sources_apt_wrapper.sh`? If so, did you get any errors?

**Comment by aucker** [comment]
Yes, I did, after running the `scripts/install_pulseaudio_sources_apt_wrapper.sh`, here is the output:
```sh
*[devel][~/pulseaudio-module-xrdp]$ ./scripts/install_pulseaudio_sources_apt_wrapper.sh 
- Creating jammy build root. Log file in /var/tmp/pa-build-aucker-debootstrap.log
[sudo] password for aucker: 
- Creating schroot config file /etc/schroot/chroot.d/pa-build-aucker.conf
- Copying /etc/apt/sources.list to the root
- Creating the build directory /build
- Copying the wrapped script to the build directory
- Building PA sources. Log file in /var/tmp/pa-build-aucker-schroot.log
- Copying sources out of the build root
- Removing schroot config file and build root
- All done. Configure PA xrdp module with PULSE_DIR=/home/aucker/pulseaudio.src
```
Looks like there is no error when executing above command, there is also a `pulseaudio.src` folder in my home directory, but I still get the above error

**Comment by aucker** [comment]
I finally solve this by changing the command `./bootstrap && ./configure PULSE_DIR=~/pulseaudio.src` to `./bootstrap && ./configure PULSE_DIR=/home/xuser/pulseaudio.src`, and everything works fine. I wonder why this happens, perhaps because I use the `zsh`?

**Comment by matt335672** [comment]
That could be it. Maybe zsh isn't expanding `~` in the same way as `sh`.

Does this command work for you?

```
./bootstrap && ./configure PULSE_DIR=$HOME/pulseaudio.src
```

If so I'll update the wiki.

**Comment by aucker** [comment]
Yes, this command also works for me

**Comment by aucker** [comment]
![image](https://github.com/neutrinolabs/pulseaudio-module-xrdp/assets/41871212/58147730-9d86-40d6-b724-50e27f154efb)
I just updated the wiki [page](https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/Build-on-Debian-or-Ubuntu/_compare/059baa6ab411f6c08ef02571f33a22134143bc86...0a492e207127c1f361751c1d78a384e565f9def8), hope it helps!🥳 And if there is no more questions, I will close this issue.

**Comment by matt335672** [comment]
Thanks.

You can use the $HOME syntax for sh too, so your wiki page change can be simplified a bit. Feel free to update it, or let me know and I'll do it.

**Comment by aucker** [comment]
Just updated the wiki page <3

**Comment by matt335672** [comment]
Perfect - ta. I'll close this now.
