### ISSUE TITLE
Clarification on when pulseaudio-module-xrdp is needed and when it is not

### ISSUE THREAD

**Issue by thecodygriffin** [neutrinolabs/pulseaudio-module-xrdp#111]
**Bare Metal Machine Install**
Back in August 2023, I setup my bare metal machine with Debian Bookworm 12.

After I installed xrdp, I found that I had no audio. After a bit of research, I found this, pulseaudio-module-xrdp, promptly compiled, built, and installed it.

Voila! I had audio. I was thrilled and very much appreciate this project.

```
$ lspci
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
```
```
$ lsmod | grep snd
snd_seq_dummy          16384  0
snd_hrtimer            16384  2
snd_seq                90112  13 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
snd_hda_codec_hdmi     81920  1
snd_hda_codec_realtek   172032  1
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
ledtrig_audio          16384  1 snd_hda_codec_generic
snd_hda_intel          57344  2
snd_intel_dspcfg       36864  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_hda_codec         184320  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
snd_hda_core          122880  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
snd_hwdep              16384  1 snd_hda_codec
snd_pcm               159744  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
snd_timer              49152  3 snd_seq,snd_hrtimer,snd_pcm
snd                   126976  18 snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_pcm
soundcore              16384  1 snd
```

**Virtual Machine Install**
Now, over the past few days, I have been work on setting up a Debian Bookworm 12 virtual machine using KVM/QEMU/LIBVIRT. A lot of the process that I followed back in August has been the same.

After installing xrdp and connecting for the first time, I found that I had no audio. I thought "No problem. I've done this before." and I compiled, built, and installed pulseaudio-module-xrdp referencing both my notes from August and the Wiki.

However, after completing the process, I could not get the "xrdp-sink" and "xrdp-source" options to appear in the **Output Device** and **Input Device** fields respectively on the **Sounds** page of Gnome **Settings**. No options, no sound. It didn't matter what I did.

There were no errors during the compilation, build, or installation. I know the `module-xrdp-sink.so` and `module-xrdp-source.so` modules were properly installed per `ls $(pkg-config --variable=modlibexecdir libpulse) | grep xrdp`.

I figured it had to be related to the configuration of virtual machine, so I uninstalled pulseaudio-module-xrdp with `sudo make uninstall` to restart from a known base. I then changed the sound device of the virtual machine configuration in Virtual Machine Manager from "HDA (ICH9)", which was the default when creating it, to "HDA (ICH6)" and rebooted with the intent of installing pulseaudio-module-xrdp.

However, before doing so, I thought "Why not check to see if I had working audio?" and to my surprise it did. I had audio working though the **Output Device** of "Line Out - 82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller (QEMU Virtual Machine)". I didn't even have to install the pulseaudio-module-xrdp module .

```
$ lspci
08:01.0 Audio device: Intel Corporation 82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller (rev 01)
```
```
$ lsmod | grep snd
snd_seq_dummy          16384  0
snd_hrtimer            16384  2
snd_seq                90112  13 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
snd_hda_codec_generic    98304  1
ledtrig_audio          16384  1 snd_hda_codec_generic
snd_hda_intel          57344  2
snd_intel_dspcfg       36864  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_hda_codec         184320  2 snd_hda_codec_generic,snd_hda_intel
snd_hda_core          122880  3 snd_hda_codec_generic,snd_hda_intel,snd_hda_codec
snd_hwdep              16384  1 snd_hda_codec
snd_pcm               159744  3 snd_hda_intel,snd_hda_codec,snd_hda_core
snd_timer              49152  3 snd_seq,snd_hrtimer,snd_pcm
snd                   126976  16 snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_timer,snd_pcm
soundcore              16384  1 snd
```
**Goal**
What the actual hell? Why does it work? Why was the pulseaudio-module-xrdp module required on my bare metal machine, but not the virtual machine?

Any insight would be greatly appreciated. I suspect there is something I don't know and there is an opportunity here for me (and possibly others) to learn something.

**Comment by matt335672** [comment]
Hi @thecodygriffin 

The pulseaudio-module-xrdp (and its pipewire counterpart) are required to be able to pass audio over the RDP link to the RDP client.

Your VM can be accessed remotely in one of two ways.
1) Use xrdp to start a session. In this scenario, pulseaudio-module-xrdp / pipewire-module-xrdp will pass teh audio over the RDP link to the RDP client.
2) Use `virt-viewer` on your client to connect to the VM console. If you do this, `virt-viewer` will pipe the audio from the virtual sound device to your client over the SPICE protocol.

Use whatever suits your use-case(s) best.

Does that make sense?

**Comment by thecodygriffin** [comment]
@matt335672,

Thank you for the response. It helped me identify and understand what I was experiencing.

I realized that I had the virt-viewer for by virtual machine open on the host machine while also being connected connected via RDP for the same virtual machine. The audio I thought was coming from my RDP link was actually just coming from the host machine.

A dumb mistake on my part.
