### ISSUE TITLE
configure script can't find libpulse.pc

### ISSUE THREAD

**Issue by CraigCottingham** [neutrinolabs/pulseaudio-module-xrdp#22]
I'm following the Ubuntu instructions in `README.md` and when I get to line 73:

```shell
./bootstrap && ./configure PULSE_DIR=/path/to/pulseaudio-11.1
```

`configure` throws a bunch of errors about not being able to find `libpulse.pc`. I added an additional env var to make it work for me:

```shell
./bootstrap && ./configure PULSE_DIR=/path/to/pulseaudio-11.1 PKG_CONFIG_PATH=/path/to/pulseaudio-11.1
```

I was going to PR a change to `README.md` but it looks like Travis is already building for Ubuntu, which suggests to me that it's something with my setup.

TL;DR: The invocation of `configure` might need an additional env var to work correctly.

Two other small notes, related to `README.md`:

1. If you follow the instructions to the letter, it looks like you're supposed to clone this repo in the directory containing the pulseaudio source code. I assume that's not harmful, though I opted to clone it in a different directory.
2. I had to read `./configure --help` to realize that the value of the `PULSE_DIR` env var should be the path to the pulseaudio source code, not the bin. That could probably be clarified, though TBH I'm not sure what the wording should be.

**Comment by pzhlkj6612** [comment]
I think `PULSE_DIR` should path to `/path/to/pulseaudio-NN.N` instead of `/path/to/pulseaudio-NN.N/src`, otherwise, in the progress of `make`:
```
  CC       module_xrdp_sink_la-module-xrdp-sink.lo
module-xrdp-sink.c:26:10: fatal error: config.h: No such file or directory
 #include <config.h>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:481: module_xrdp_sink_la-module-xrdp-sink.lo] Error 1
```
`config.h` is in the root of `/path/to/pulseaudio-NN.N` folder.

**Comment by pzhlkj6612** [comment]
And, if you've installed `libpulse-dev` package, the argument `PKG_CONFIG_PATH` is not needed.

`libpulse.pc` will be placed at `/usr/lib/x86_64-linux-gnu/pkgconfig/libpulse.pc`.

<br/>

PS:

The error message in the progress `configure`:
```
Package libpulse was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpulse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpulse' found
```

**Comment by metalefty** [comment]
Solution provided, thanks!
