### ISSUE TITLE
I had to manually modify /etc/xrdp/pulse/default.pa at the end of the installation procedure

### ISSUE THREAD

**Issue by Rrogntudju** [neutrinolabs/pulseaudio-module-xrdp#23]
I followed the «other distro» installation steps and it went fine. After reopening a session with xrdp, the session was still using the null sink.
I had to modify /etc/xrdp/pulse/default.pa to make it work.

Original content:
.nofail
.fail
load-module module-augment-properties
load-module module-always-sink
.ifexists /var/lib/xrdp-pulseaudio-installer/module-xrdp-sink.so
load-module /var/lib/xrdp-pulseaudio-installer/module-xrdp-sink.so
.endif
.ifexists /var/lib/xrdp-pulseaudio-installer/module-xrdp-source.so
load-module /var/lib/xrdp-pulseaudio-installer/module-xrdp-source.so
.endif
load-module module-native-protocol-unix

Modified content:
.nofail
.fail
load-module module-augment-properties
load-module module-always-sink
.ifexists /usr/lib/pulse-11.1/modules/module-xrdp-sink.so
load-module /usr/lib/pulse-11.1/modules/module-xrdp-sink.so
.endif
.ifexists /usr/lib/pulse-11.1/modules/module-xrdp-source.so
load-module /usr/lib/pulse-11.1/modules/module-xrdp-source.so
.endif
load-module module-native-protocol-unix

**Comment by Rrogntudju** [comment]
Hi!
It's Ubuntu Neon upgraded to 18.04. xrdp and pulseaudio-module-xrdp were installed after the upgrade.

**Comment by Rrogntudju** [comment]
I tried the Ubuntu install at first. But i got errors with «apt build-dep pulseaudo» and «apt source pulseaudio». After some readings, i saw that i had to enable the sources of the source packages (deb-src lines). I did that but i was still getting the same errors. With some further readings..., i found that the pulseaudio package was missing the source info so i decided to install with the tar file.
dpkg -s pulseaudio
Package: pulseaudio
Status: install ok installed
Priority: optional
Section: sound
Installed-Size: 3980
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1:11.1-1ubuntu7.1

**Comment by metalefty** [comment]
I confirmed Ubuntu/Debian requires default.pa modification.

**Comment by mirabilos** [comment]
I confirm Debian buster doesn't ;-) but yes, anything before Debian xrdp 0.9.8-2 would.

**Comment by rhy-ama** [comment]
Ubuntu 18.04.1 package version is 0.9.5 requires this modification.

**Comment by Simsalaba** [comment]
I needed to do this on Raspbian Buster to get it to work as well. RPI4 8GB.

Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

**Comment by metalefty** [comment]
I think this distro specific patch is already included Debian:
https://salsa.debian.org/debian-remote-team/xrdp/-/commit/40160f40bb630fc8d330e9d2de895a7739015664
