### ISSUE TITLE
LICENSE: switch to LGPLv2.1

### ISSUE THREAD

**Issue by jcpunk** [neutrinolabs/pulseaudio-module-xrdp#36]
One of the source files lists APL2 another lists GPL2,  others have no identification.  Can the license information be clarified for this code?

**Comment by jsorg71** [comment]
Yes, I noticed that too.  Since these modules run in process and pulseaudio is GPL2 I guess they should all be GPL2.

**Comment by metalefty** [comment]
Ideally, we need to get approval of re-definite license from all contributors however, fortunately, more than 80% of commits are made by Jay and speidy and me. The rest commits are only 10. If the changes are trivial enough, license change can be done without their approval.

At least I'm OK with changing everything I contributed to GPLv2.

**Comment by metalefty** [comment]
Update: 

I've looked through all commits, I think we can change the license. 

metalefty, jsorg71, speidy and LK2000 are members of the xrdp project. So we don't need to get approval of these 4 of us.

NatureShadow contributed 1 commit but it was a simple document change. proski is a former outside contributor but his contributions are also very simple. CI fixes, suppress warnings and updating gitignore.

**Comment by metalefty** [comment]
I noticed PulseAudio's license has been changed to LGPLv2.1.
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/LICENSE
