### ISSUE TITLE
Wiki updating?

### ISSUE THREAD

**Issue by mirabilos** [neutrinolabs/pulseaudio-module-xrdp#40]
I found out one cannot pull request Wiki pages on GitHub.

I just went through the PA module setup process on Debian buster and would like to correct some small inconsistencies (paths, use of sudo for some parts and not for others when running as regular user, etc.), update with Debian stable info, and most importantly, a workaround for [Debian bug #923203 — no sound on Debian buster with sysvinit](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923203) (namely, adding `autospawn = yes` to `~/.config/pulse/client.conf).

How would I go submitting those?

**Comment by metalefty** [comment]
@mirabilos Sorry for the delay. I've allowed Wiki editing to everyone. Feel free to edit it.
