### ISSUE TITLE
Sink and source not detected

### ISSUE THREAD

**Issue by calvss** [neutrinolabs/pulseaudio-module-xrdp#66]
I'm trying to follow the build instructions on Debian Bookworm, apt downloaded PulseAudio-15.0+dfsg1

At first I got the same config.h problem as #58, but by copying the file from `PulseAudio-15.0+dfsg1/build/config.h` to `PulseAudio-15.0+dfsg1/config.h` I got it to make.

The rest of the instructions worked as-is, and `ls $(pkg-config --variable=modlibexecdir libpulse)`  showed `module-xrdp-sink.la module-xrdp-sink.so module-xrdp-source.la module-xrdp-source.so` was present.

Problem is, `pavumeter` shows it's using "Dummy Output".
I checked with `pacmd` `list-sinks` and `list-sources` and the xrdp sink/source isn't visible.

I get:
```
1 sink(s) available.
  * index: 0
	name: <auto_null>
```
```
1 source(s) available.
  * index: 0
	name: <auto_null.monitor>
```

Am I missing something to configure?

p.s. I'm using the windows Remote Desktop client

**Comment by matt335672** [comment]
Hi @calvss 

It looks as if the modules aren't being loaded.

As it happens, we're currently in the process of reworking this entire area.

The original module design was to use Pulseaudio (PA) in [system mode](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/). However, pretty much all distributions decided that this wasn't sensible, and that PA was best started in per-user mode. We're reworking the modules to better support this. At the same time we're updating them to work with PA version 15, which is what you are using.

Discussion neutrinolabs/xrdp#1910 is worth looking at to get some background on this.

As far as solving your problem goes, may I trouble you to have a look at [this conversation](https://gitter.im/neutrinolabs/xrdp-questions?at=617d56fdfb3dcd4e88596863) on gitter? It's primarily about CentOS 8, but should equally apply to Debian/Ubuntu.

Essentially, you'll need to rebuild the modules against a test branch in my repository which has the fixes for PA 15, plus some additional support for loading modules when a session starts.

If you're not happy about building against my repository, or you've got any other questions about the above please get back to me.

**Comment by calvss** [comment]
Thanks! Your branch worked perfectly, just had to reboot the remote machine after ```make install```

**Comment by matt335672** [comment]
Thanks also for the swift feedback - it really helps the release process for us.

**Comment by matt335672** [comment]
As a final comment, I can't explain why a reboot should be necessary but I'm glad you got it working.
