### ISSUE TITLE
wrapped_script: Permission denied -- proposed fix

### ISSUE THREAD

**Issue by orthorhombic** [neutrinolabs/pulseaudio-module-xrdp#79]
On my ubuntu 22.04 system, when copying `wrapped_script` it's getting moved over (sudo cp) and gets file permissions that schroot can't run with as a regular user. I think this could be fixed by changing to `chmod a+rx` (this worked for me) or switching to `cp -a` (didn't test, but probably would work).

Error log (/var/tmp/pa-build-$USER-schroot.log):
```
root.log
Reading package lists...
Building dependency tree...
lsb-release is already the newest version (11.1.0ubuntu4).
sudo is already the newest version (1.9.9-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/bin/sh: 0: cannot open /wrapped_script: Permission denied
```

Lines of interest:
```
sudo cp $WRAPPED_SCRIPT $BUILDROOT/wrapped_script || exit $?
sudo chmod +x $BUILDROOT/wrapped_script || exit $?
```

Proposed change:
```
sudo cp $WRAPPED_SCRIPT $BUILDROOT/wrapped_script || exit $?
sudo chmod a+rx $BUILDROOT/wrapped_script || exit $?
```

https://github.com/neutrinolabs/pulseaudio-module-xrdp/blob/93307a6b0b976b2bfd8cb0f6c9dca7bb10114096/scripts/install_pulseaudio_sources_apt_wrapper.sh#L215

**Comment by matt335672** [comment]
Thanks for that @orthorhombic 

`+x` should be the same as `a+x` according to chmod(1).

I'd like to query a bit more about what's going on on your system, if I may, so we can be sure we fully understand the problem.

Can you do the following for me?

After the `sudo cp` line, can you remove the `chmod +x line and replace it with :-

```sh
umask
ls -ld $BUILDROOT
ls -l $BUILDROOT/wrapped_script
sudo chmod +x $BUILDROOT/wrapped_script || exit $?
ls -l $BUILDROOT/wrapped_script
```

Then post the output back here.

That would be great - thanks.

**Comment by orthorhombic** [comment]
Thanks for the quick response!

I don't think `+x` and `a+x` are the same. `+x` is only for the user (root in this case).  `a+x` or `o+x` is for everyone. I think I have a more restrictive umask on `/var` than expected that may be the cause of this. Below is the requested output. For this to run as a different user, `+rx` permissions are needed for the user. I have to run now, but can help troubleshoot more later if necessary.



```
- Creating jammy build root. Log file in /var/tmp/pa-build-default-debootstrap.log
- Creating schroot config file /etc/schroot/chroot.d/pa-build-default.conf
- Copying the wrapped script to the root
0007
drwxr-xr-x 17 root root 4096 May 12 08:16 /var/lib/pa-build/default
-rwxr-x--- 1 root root 4686 May 12 08:16 /var/lib/pa-build/default/wrapped_script
-rwxr-x--- 1 root root 4686 May 12 08:16 /var/lib/pa-build/default/wrapped_script
- Building PA sources. Log file in /var/tmp/pa-build-default-schroot.log
- ** schroot failed. Check log file /var/tmp/pa-build-default-schroot.log
```

**Comment by matt335672** [comment]
And thanks for your quick response!

Leave it with me - I've got enough to put a PR together now. I'll probably use the install command for this rather than cp/chown as that's exactly what it's intended for.

**Comment by matt335672** [comment]
I've merged another fix too, so the script has changed quite a bit, but it should work for you now.

**Comment by orthorhombic** [comment]
Thanks @matt335672 !

I can successfully install and get audio redirects after running `pulseaudio --start` in a terminal. Auto starting doesn't seem to be working, and I suspect this is due to the same restrictive umask issues.  `/usr/libexec/pulseaudio-module-xrdp/load_pa_modules.sh` and `/etc/xdg/autostart/pulseaudio-xrdp.desktop` appear to be installed fine, but perhaps also need to be explicitly placed with 755 on the folders.

Want me to open a new issue for this or keep it here?

`sudo ls -la /usr/libexec/` output:
```
...
-rwxr-xr-x  1 root root  121504 Feb 26 06:11 polkitd
-rwxr-xr-x  1 root root   67968 Mar  5 12:17 power-profiles-daemon
drwxr-x---  2 root root    4096 May 12 23:41 pulseaudio-module-xrdp
-rwxr-xr-x  1 root root   14736 Feb 16 09:20 qmi-proxy
-rwxr-xr-x  1 root root  109024 Feb 17 13:39 rhythmbox-metadata
...
```

**Comment by matt335672** [comment]
Please open an issue - I think you're exactly right.

Or do you want to try a PR yourself?
