### ISSUE TITLE
Pulseaudio server not supported on Ubuntu 22.10

### ISSUE THREAD

**Issue by volo-zyko** [neutrinolabs/pulseaudio-module-xrdp#89]
Previously on Ubuntu 22.04 these modules worked. The sound was not perfect (very slow and stuttering) but it was audible. Today I decided to upgrade to a newer Ubuntu version and since then, despite the code built and installed fine, I don't see xrdp sink output device in GNOME Settings. Obviously, neither paplay nor YouTube in Firefox don't produce any sound. Debugging `load_pa_modules.sh` showed the following malformed behavior.

```
$> sh -x /usr/libexec/pulseaudio-module-xrdp/load_pa_modules.sh
+ status=0
+ [ -n 1 -a -n /run/xrdp/sockdir ]
+ [ -z xrdp_chansrv_audio_out_socket_10 -o -z xrdp_chansrv_audio_in_socket_10 ]
+ pactl unload-module module-xrdp-sink
+ pactl unload-module module-xrdp-source
+ pactl load-module module-xrdp-sink xrdp_socket_path=/run/xrdp/sockdir xrdp_pulse_sink_socket=xrdp_chansrv_audio_out_socket_10
Failure: No such entity
+ echo ? Can't load pulseaudio xrdp-sink
? Can't load pulseaudio xrdp-sink
+ status=1
+ pactl load-module module-xrdp-source xrdp_socket_path=/run/xrdp/sockdir xrdp_pulse_source_socket=xrdp_chansrv_audio_in_socket_10
Failure: No such entity
+ echo ? Can't load pulseaudio xrdp-source
? Can't load pulseaudio xrdp-source
+ status=1
+ exit 1
```

Then I tried to trace pactl (don't know if it makes any sense) but it didn't give me any new clue. I attached the log here. Maybe someone will see anything interesting in it - [pactl.log](https://github.com/neutrinolabs/pulseaudio-module-xrdp/files/10329475/pactl.log).

What else can I do to track the problem down?

**Note**: Despite I upgraded Ubuntu (i.e. not installed it from scratch) I purged everything related to pulseaudio and alsa and reinstalled those packages. After that I rebuilt XRDP modules again.
**Another note**: There are no problems with the sound in non-XRDP (local) setup.

**Comment by matt335672** [comment]
Having a quick browse of the sources suggests that the error is generated by the pulseaudio server and passed back to pactl.

Couple of things to do:-
1) Check the modules are in the right location, and the module file permissions are right. Because the PA server is running as the logged-in user, the modules should be owned by root, but be world-readable and executable.
2) Use `pacmd set-log-level 4` to set the logging level to debug, and then `journalctl -f --user-unit=pulseaudio` in a separate window to tail the pulseaudio log. Then run the script again.

**Comment by volo-zyko** [comment]
1. Result of `ls -l $(pkg-config --variable=modlibexecdir libpulse) | grep xrdp`:

```
-rwxr-xr-x 1 root root    986 Jan  1 22:13 module-xrdp-sink.la
-rwxr-xr-x 1 root root  86216 Jan  1 22:13 module-xrdp-sink.so
-rwxr-xr-x 1 root root    998 Jan  1 22:13 module-xrdp-source.la
-rwxr-xr-x 1 root root  77952 Jan  1 22:13 module-xrdp-source.so
```

2. `pacmd set-log-level 4` immediately reports `No PulseAudio daemon running, or not running as session daemon`. At the same time `pactl info` prints the following:

```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 92
Tile Size: 65472
User Name: rei
Host Name: serv
Server Name: PulseAudio (on PipeWire 0.3.58)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1b.0.iec958-stereo
Default Source: alsa_input.pci-0000_00_1b.0.analog-stereo
Cookie: 01a0:110a
```

And there is now no `pulseaudio` service in the new Ubuntu. It seems like they changed to PipeWire... What it means in terms of XRDP is a mystery.

**Comment by matt335672** [comment]
I'm not familiar with pipewire at all, but it may be that what you're looking at is an emulation of the pulseaudio server provided for pulseaudio clients.

It doesn't look like pulseaudio is supported any more following 22.04 LTS:-

https://discourse.ubuntu.com/t/pipewire-as-a-replacement-for-pulseaudio/28489

We don't have a solution for this at the moment I'm afraid. See also neutrinolabs/xrdp#2023

**Comment by theycallme-west** [comment]
You could always revert back to Pulseaudio. This worked for me after I upgraded to Debian 12:

unmask PulseAudio:

systemctl --user unmask pulseaudio

Disable the pipewire-pulse service:

systemctl --user --now disable pipewire-pulse

Re-enable the PulseAudio services:

systemctl --user --now enable pulseaudio.service pulseaudio.socket

**Comment by matt335672** [comment]
Both - please look at neutrinolabs/xrdp#2023 for a solution to this.

I'm sorry I didn't update this issue earlier. I'll close this one now. Please move future discussions to neutrinolabs/xrdp#2023
